# Copyright (c) 2026 Carles Marín. All rights reserved.
# Carles Marín <karlesmarin@gmail.com>, con Claude (Anthropic) como asistente.
# cuadrado.sage -- is V*V = R-bar for every nonzero stable V?  The hypothesis of Corollary 18, tested.
# What: (A) random cyclic G-stable subspaces of R-bar: dim V against dim(V*V), and whether dim V > d/2
#       is what decides; (B) the obstruction: V*V = V exactly when V is spanned by the characters of a
#       subgroup, the constants being the smallest case; (C) a stable LINE is its own square (a character
#       line, not the constants: the U-twist), and that is exactly what the ladder produces, so the
#       counterexample is realised inside the family.
# Run: sh sg.sh cuadrado.sage
load("inst.sage")

def reps(n):
    return [u for u in range(1, n) if gcd(u, n) == 1 and u < n - u]

def modulo_generado(n, p, v):
    """F_p[G]-module generated by the vector v (coordinates indexed by G = (Z/n)^x / +-1)."""
    un = reps(n); d = len(un)
    idx = {}
    for i, u in enumerate(un):
        idx[u] = i; idx[n - u] = i
    filas = []
    for a in un:
        filas.append([v[idx[(a * un[i]) % n]] for i in range(d)])
    M = matrix(GF(p), filas)
    return M.row_space()

def cuadrado(U):
    """span of the coordinatewise products of a basis of U"""
    B = U.basis()
    if not B: return U.parent().zero_submodule() if hasattr(U.parent(), "zero_submodule") else U
    F = U.base_ring(); d = len(B[0])
    pr = [[B[i][k] * B[j][k] for k in range(d)] for i in range(len(B)) for j in range(i, len(B))]
    return matrix(F, pr).row_space()

print("=== (A) does dim V > d/2 decide?  cyclic stable subspaces, random generators ===")
print("q'  p  d  | dim V  dim(V*V)  | V*V=R-bar  2dimV>d")
tot = disc = 0
chico_lleno = chico_no = 0
set_state = 12345
for qp in [7, 9, 11, 13, 15, 17, 19, 23, 25]:
    for p in [3, 5, 7, 11]:
        if qp % p == 0: continue
        d = euler_phi(qp) // 2
        if d < 3: continue
        F = GF(p)
        set_random_seed(set_state); set_state += 1
        for ensayo in range(12):
            v = [F.random_element() for _ in range(d)]
            if all(x == 0 for x in v): continue
            V = modulo_generado(qp, p, v)
            if V.dimension() == 0: continue
            VV = cuadrado(V)
            lleno = (VV.dimension() == d)
            grande = (2 * V.dimension() > d)
            tot += 1
            if grande and not lleno: disc += 1
            if not grande:
                if lleno: chico_lleno += 1
                else: chico_no += 1
            if not grande or (grande and not lleno):
                print("%-3d %-2d %-2d | %-6d %-9d | %-10s %s" % (
                    qp, p, d, V.dimension(), VV.dimension(), lleno, grande))
print("ensayos=%d ; con 2dimV>d y V*V != R-bar: %d (debe ser 0)" % (tot, disc))
print("con 2dimV<=d: %d llenan y %d no  --> la hipotesis dim V > d/2 NO es superflua" % (chico_lleno, chico_no))
print("")

print("=== (B) the obstruction: subgroups, and the constants ===")
for qp in [7, 11, 13]:
    for p in [3, 5]:
        if qp % p == 0: continue
        d = euler_phi(qp) // 2
        F = GF(p)
        uno = modulo_generado(qp, p, [F(1)] * d)
        q1 = cuadrado(uno)
        print("q'=%-3d p=%-2d d=%-2d | constantes: dim V=%d, dim(V*V)=%d  -> %s" % (
            qp, p, d, uno.dimension(), q1.dimension(),
            "V*V = V, no llena" if q1.dimension() == uno.dimension() < d else "?"))
print("")

print("=== (C) the ladder layer is a stable line: the obstruction, inside the family ===")
def capas_sub(I, K):
    R, F, phin = I.R, I.F, I.phin
    rows = [R(list(r)) for r in I.B.rows()]
    dphi = phin.degree(); out = []
    for i in range(K):
        Pi = phin**i
        if i == 0:
            elems = rows
        else:
            M = matrix(F, [I.vec(f % Pi, Pi.degree()) for f in rows])
            ker = M.left_kernel().basis_matrix()
            elems = [sum(ker[k][j] * rows[j] for j in range(len(rows))) for k in range(ker.nrows())]
        if not elems:
            out.append(matrix(F, 0, dphi)); continue
        img = matrix(F, [I.vec((f // Pi) % phin, dphi) for f in elems]).echelon_form()
        out.append(img.matrix_from_rows(range(img.rank())))
    return out

for (p, qp, M) in [(3, 5, 1), (3, 7, 1), (3, 11, 1), (5, 7, 1), (5, 11, 1)]:
    N = p * M
    if (N * qp) % 2 == 0: continue
    m = (N * qp - 1) // 2
    v = 2
    while 2 * m >= p**v * qp or euler_phi(p**v) < p + 2: v += 1
    q = p**v * qp
    I = Img(q, p, m, min(euler_phi(p**v), p + 2))
    G = capas_sub(I, min(euler_phi(p**v), p + 2))
    lad = G[p - 1]                      # la capa de la escalera, grado P - 1 = p - 1 con a = 1
    d = euler_phi(qp) // 2
    R = I.R; phin = I.phin
    base = [R(list(r)) for r in lad.rows()]
    cua = matrix(I.F, [I.vec((b1 * b2) % phin, phin.degree())
                       for i, b1 in enumerate(base) for b2 in base[i:]]).rank() if base else 0
    cte = all((b % phin).degree() <= 0 for b in base)
    print("q'=%-3d p=%-2d m=%-4d | d=%-2d dim gr_{p-1}=%d  dim(gr*gr)=%d  %s ; constantes: %s (es una recta de caracter)" % (
        qp, p, m, d, lad.nrows(), cua, "NO llena" if cua < d else "llena", cte))
