# Copyright (c) 2026 Carles Marín. All rights reserved.
# Carles Marín <karlesmarin@gmail.com>, con Claude (Anthropic) como asistente.
# item1.py -- semigroup certification of the conductor exponent on the 10 rows of fig_perfil.
# What: layers by dims_B (K=min(9,E)); closure F = full + Sigma (Sigma generated by s>=1 with W_s>0, optionally + E);
#       certified e = least a with [a,inf) in F and layer a-1 computed and not full.
# Run: python item1.py
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from perfil_W import dims_B
from math import gcd

def phi(n):
    return sum(1 for k in range(1, n + 1) if gcd(k, n) == 1)

def certify(W, d, extra_gens=()):
    K = len(W)
    gens = sorted(set([s for s in range(1, K) if W[s] > 0] + list(extra_gens)))
    full = set(i for i in range(K) if W[i] == d)
    # bound: work up to L; F = full + Sigma, iterate (forced full layers are new generators)
    L = 4 * K + 4 * max(gens + [1]) + 50
    F = set(full)
    changed = True
    while changed:
        changed = False
        G = sorted(set(gens) | set(x for x in F if x >= 1))
        for a in list(F):
            for s in G:
                if a + s <= L and a + s not in F:
                    F.add(a + s); changed = True
    # find least a such that [a, L] subset F and a window of length min gen inside computed-by-closure is ensured
    if not G:
        return None, F, G
    s0 = min(G)
    best = None
    for a in range(L - s0, -1, -1):
        if all(x in F for x in range(a, L + 1)):
            best = a
        else:
            break
    # [best, L] in F with L - best >= s0 ensures all >= best by adding s0 repeatedly
    if best is None or L - best < s0:
        return None, F, G
    return best, F, G

casos = [(3, 5, 2, 7), (3, 7, 2, 10), (3, 11, 2, 16), (3, 13, 2, 19),
         (5, 7, 2, 17), (5, 9, 2, 22), (5, 11, 2, 27), (5, 13, 2, 32),
         (7, 3, 2, 10), (7, 5, 2, 17)]
claims = {(7, 45): 5, (10, 63): 6, (16, 99): 3, (19, 117): 5, (22, 225): 8, (27, 275): 8, (32, 325): 5}
for (p, n, v, m) in casos:
    q = p**v * n
    E = phi(p**v)
    K = min(9, E)
    d = phi(n) // 2
    if n in (1, 2, 3, 4, 6):
        print("A_%d(%d) p=%d q'=%d  EXCLUDED (q' in {1,2,3,4,6})" % (m, q, p, n))
        continue
    dB = dims_B(q, p, m, n, K)
    W = [dB[0]] + [dB[i] - dB[i - 1] for i in range(1, K)]
    for tag, extra in (("Sigma", ()), ("Sigma+E", (E,))):
        a, F, G = certify(W, d, extra)
        if a is None:
            status = "no tail certified"
            e_cert = None
        else:
            below = a - 1
            if a == 0:
                status = "e=0?"; e_cert = 0
            elif below < K and W[below] < d:
                status = "e certified = %d" % a; e_cert = a
            elif below < K:
                status = "BUG"; e_cert = None
            else:
                status = "only e<=%d (layer %d not computed)" % (a, below); e_cert = None
        forced = sorted(x for x in F if x < 2 * K and not (x < K and W[x] == d))
        print("A_%d(%d) p=%d q'=%d d=%d E=%d K=%d W=%s gens=%s forced(<2K)=%s -> [%s] %s  claim=%s %s" % (
            m, q, p, n, d, E, K, W, [g for g in G if g < 2 * K], forced, tag, status, claims.get((m, q)),
            "" if claims.get((m, q)) is None else ("AGREE" if claims.get((m, q)) == e_cert else "DIFFER")))
