#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""P3a.py -- the order generated by a column of the SU(n)_k S-matrix, computed.

  Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)

A single file, Python 3 standard library only.  No Sage, no numpy, nothing to install.  Every
number is an exact integer; nothing is decided in floating point.

WHAT IT COMPUTES  (each routine is named after the statement of the note it implements)

    espectro(n, k, mu)      the reduced spectrum T of g_mu in F_p, the order m of the central
                            scalar, the charge and the conformal weight          (Sec. 2)
    gamma_T(T, p)           the semigroup of moments  < e, j : M_hj(T) != 0 >      (Thm. moments)
    s_exacto(T, p)          the exact semigroup S_T, b_j by Teichmuller lifts mod p^K
                                                                             (Thm. exact semigroup)
    semigrupo(gens)         gaps, conductor, symmetry, minimal generators of a numerical semigroup
    delta_red(T, p)         delta(T) = v_p[O_E : C_T] as an index of integer lattices, NOT through
                            the semigroup                                       (Prop. decomposition)
    orden_columna(n, k, mu) [O:A], [A:f] and the Gorenstein test of the column, by integer lattices
                            inside Z[zeta_(n(n+k))]; any height n+k        (Cor. Gorenstein, Sec. 7)
    maximales(p, n)         N_0(p, n) by the closed formula                 (Prop. maximal columns)
    columna(n, k, mu)       all of the above for one column, prime height

USAGE
    python P3a.py autotest                 recompute the worked examples of the note
    python P3a.py columna n k mu_1 ... mu_{n-1}
    python P3a.py espectro p t_1 ... t_n   semigroups and delta of a centred spectrum
    python P3a.py maximales p n            N_0(p, n), formula and enumeration

    As a library:  from P3a import espectro, gamma_T, s_exacto, semigrupo, delta_red,
                                    orden_columna, maximales, columna

WHAT IT DECLINES
    espectro, columna, s_exacto, delta_red   height n+k not an odd prime (the prime-height
                            statements of the note do not apply); use orden_columna there.
    s_exacto                a b_j it cannot resolve modulo p^K and that could change S_T.
    orden_columna           n*(n+k) above ORDEN_MAX (degree of the cyclotomic field too large for
                            exact lattice arithmetic in seconds).

Public domain (CC0).
"""
import sys
from fractions import Fraction
from itertools import combinations
from math import comb, gcd

ORDEN_MAX = 130   # largest N = n(n+k) accepted by orden_columna
K_TEICH = 12      # p-adic precision of the Teichmuller lifts in s_exacto


# --------------------------------------------------------------------------- arithmetic

def es_primo(n):
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True


def phi(m):
    return sum(1 for a in range(1, m + 1) if gcd(a, m) == 1)


def vp(x, p):
    x, k = abs(x), 0
    while x and x % p == 0:
        x //= p
        k += 1
    return k


def factor_str(m):
    out, q = [], 2
    while m > 1:
        e = 0
        while m % q == 0:
            m //= q
            e += 1
        if e:
            out.append("%d^%d" % (q, e) if e > 1 else str(q))
        q += 1
    return "*".join(out) or "1"


def pesos(n, k):
    """all integrable weights (Dynkin labels mu_1..mu_{n-1}) of SU(n) at level k."""
    def rec(i, rest):
        if i == n - 1:
            yield ()
            return
        for a in range(rest + 1):
            for r in rec(i + 1, rest - a):
                yield (a,) + r
    return list(rec(0, k))


# --------------------------------------------------------------------------- the spectrum

def ells(n, mu):
    """l_i = sum_{j >= i} mu_j + n - i, i = 1..n (mu_n = 0)."""
    mu = list(mu) + [0] * (n - len(mu))
    return [sum(mu[i - 1:n]) + n - i for i in range(1, n + 1)]


def espectro(n, k, mu):
    """T subset F_p (sorted), m = order of eta_mu, charge c(mu) mod n, conformal weight mod 1."""
    p = n + k
    if not (p > 2 and es_primo(p)):
        raise ValueError("height n+k = %d is not an odd prime" % p)
    if len(mu) != n - 1 or min(mu) < 0 or sum(mu) > k:
        raise ValueError("mu is not an integrable weight of SU(%d)_%d" % (n, k))
    l = ells(n, mu)
    L = sum(l)
    v = pow(n, -1, p)
    u = (1 - v * n) // p
    T = sorted((x - v * L) % p for x in l)
    ex = (-u * L) % n
    m = n // gcd(n, ex) if ex else 1
    Q = n * sum(x * x for x in l) - L * L           # n |mu+rho|^2
    rho2 = Fraction(n * (n * n - 1), 12)
    peso = (Fraction(Q, n) - rho2) / (2 * p) % 1
    carga = sum((i + 1) * a for i, a in enumerate(mu)) % n
    return dict(p=p, T=T, m=m, carga=carga, peso=peso, Q=Q, L=L, l=l)


def estabilizador(T, p):
    Ts = set(T)
    return [a for a in range(1, p) if {a * t % p for t in T} == Ts]


def momento(T, r, p):
    return sum(pow(t, r, p) for t in T) % p


# --------------------------------------------------------------------------- semigroups

def semigrupo(gens):
    """gaps, conductor, genus, symmetry and minimal generators of <gens> (gcd must be 1)."""
    gens = sorted(set(g for g in gens if g > 0))
    g0 = 0
    for x in gens:
        g0 = gcd(g0, x)
    if g0 != 1:
        raise ValueError("generators with common factor %d" % g0)
    top = gens[0] * gens[-1] + 2
    S = [False] * (top + 1)
    S[0] = True
    for x in range(1, top + 1):
        S[x] = any(x >= a and S[x - a] for a in gens)
    huecos = [x for x in range(top + 1) if not S[x]]
    c = huecos[-1] + 1 if huecos else 0
    mins = [a for a in gens if not any(S[x] and S[a - x] for x in range(1, a))]
    return dict(huecos=huecos, genero=len(huecos), conductor=c, simetrico=(c == 2 * len(huecos)),
                minimales=mins, multiplicidad=mins[0])


def gamma_T(T, p):
    """generators of Gamma_T = < e, j : 1 <= j < e, M_hj(T) != 0 >."""
    h = len(estabilizador(T, p))
    e = (p - 1) // h
    return [e] + [j for j in range(1, e) if momento(T, h * j, p)]


def s_exacto(T, p, K=K_TEICH):
    """generators of S_T = < e, j + e b_j >, b_j = v_p(sum_{t != 0} omega(t)^{hj})."""
    if not (p > 2 and es_primo(p)):
        raise ValueError("p = %d is not an odd prime" % p)
    h = len(estabilizador(T, p))
    e = (p - 1) // h
    mod = p ** K
    gens, abiertos = [e], []
    for j in range(1, e):
        B = sum(pow(pow(t, p ** (K - 1), mod), h * j, mod) for t in T if t % p) % mod
        if B == 0:
            abiertos.append(j)
            continue
        gens.append(j + e * vp(B, p))
    if abiertos:
        c = semigrupo(gens)["conductor"]
        if any(j + e * K < c for j in abiertos):
            raise ValueError("a b_j beyond p^%d could change S_T; raise K" % K)
    return gens


# --------------------------------------------------------------------------- integer lattices

def xgcd(a, b):
    x0, y0, x1, y1 = 1, 0, 0, 1
    while b:
        q, a, b = a // b, b, a % b
        x0, x1 = x1, x0 - q * x1
        y0, y1 = y1, y0 - q * y1
    return a, x0, y0


def echelon(rows, ncp):
    """unimodular row reduction on the first ncp columns (Hermite form there).
    Returns (pivot rows, remaining rows, which vanish on those columns)."""
    rows = [list(r) for r in rows]
    r = 0
    for col in range(ncp):
        idx = [i for i in range(r, len(rows)) if rows[i][col]]
        if not idx:
            continue
        rows[r], rows[idx[0]] = rows[idx[0]], rows[r]
        for i in range(r + 1, len(rows)):
            b = rows[i][col]
            if not b:
                continue
            a = rows[r][col]
            g, s, t = xgcd(a, b)
            pr, ri = rows[r], rows[i]
            rows[r] = [s * x + t * y for x, y in zip(pr, ri)]
            rows[i] = [(-b // g) * x + (a // g) * y for x, y in zip(pr, ri)]
        if rows[r][col] < 0:
            rows[r] = [-x for x in rows[r]]
        pv = rows[r][col]
        for i in range(r):
            f = rows[i][col] // pv
            if f:
                rows[i] = [x - f * y for x, y in zip(rows[i], rows[r])]
        r += 1
    return rows[:r], [x for x in rows[r:] if any(x)]


def _det_tri(M):
    d = 1
    for i, r in enumerate(M):
        d *= r[i]
    return abs(d)


def _en_modulo(M, x):
    """is x in the Z-span of the square Hermite basis M (upper triangular)?"""
    c = []
    for j in range(len(M)):
        v = x[j] - sum(c[i] * M[i][j] for i in range(j))
        if v % M[j][j]:
            return False
        c.append(v // M[j][j])
    return True


def delta_red(T, p, con_base=False):
    """delta(T) = v_p[O_E : C_T]: C_T = Z[e_1(zeta^T), ..., e_{n-1}(zeta^T)] in Z[zeta_p],
    O_E spanned by the Gauss periods of the H_T-classes; the index is a lattice determinant."""
    if not (p > 2 and es_primo(p)):
        raise ValueError("p = %d is not an odd prime" % p)
    T = sorted(t % p for t in T)
    H = estabilizador(T, p)
    clases, visto = [], set()
    for x in range(1, p):
        if x not in visto:
            cl = sorted({a * x % p for a in H})
            visto |= set(cl)
            clases.append(cl)

    def norma(v):
        return [x - v[0] for x in v]          # zeta^0 = -(zeta + ... + zeta^{p-1})

    def mul(a, b):
        w = [0] * p
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        w[(i + j) % p] += x * y
        return norma(w)

    def coords(v):
        for cl in clases:
            if len({v[x] for x in cl}) != 1:
                raise AssertionError("element outside E_T")
        return [v[cl[0]] for cl in clases]

    def expande(c):
        v = [0] * p
        for val, cl in zip(c, clases):
            for x in cl:
                v[x] = val
        return v

    n = len(T)
    gens = []
    for j in range(1, n):
        v = [0] * p
        for S in combinations(T, j):
            v[sum(S) % p] += 1
        gens.append(norma(v))
    uno = norma([1] + [0] * (p - 1))
    e = len(clases)
    M, _ = echelon([coords(x) for x in [uno] + gens], e)
    while True:
        elems = [expande(c) for c in M]
        prods = [mul(a, g) for a in elems for g in gens]
        M2, _ = echelon([coords(x) for x in elems + prods], e)
        if M2 == M:
            break
        M = M2
    if len(M) != e:
        raise AssertionError("C_T does not have full rank")
    det = _det_tri(M)
    if det != p ** vp(det, p):
        raise AssertionError("index %d is not a power of p" % det)
    d = vp(det, p)
    return (d, M) if con_base else d


def exponente_p(T, p):
    """(p O_E in C_T, O_E in C_T), decided on the lattice basis, not through the semigroup."""
    d, M = delta_red(T, p, con_base=True)
    e = len(M)
    unit = [[int(i == j) for j in range(e)] for i in range(e)]
    return all(_en_modulo(M, [p * x for x in r]) for r in unit), all(_en_modulo(M, r) for r in unit)


# --------------------------------------------------------------------------- any height

def _cyclotomic(N, memo={}):
    if N in memo:
        return memo[N]
    P = [-1] + [0] * (N - 1) + [1]
    for d in range(1, N):
        if N % d == 0:
            b = _cyclotomic(d)
            a = P[:]
            out = [0] * (len(a) - len(b) + 1)
            for i in range(len(out) - 1, -1, -1):
                c = a[i + len(b) - 1] // b[-1]
                out[i] = c
                for j, bj in enumerate(b):
                    a[i + j] -= c * bj
            P = out
    memo[N] = P
    return P


class _Cyc:
    """Z[zeta_N] in the power basis 1, zeta, ..., zeta^(phi(N)-1)."""
    def __init__(self, N):
        self.N = N
        self.f = _cyclotomic(N)
        self.d = len(self.f) - 1

    def reduce(self, v):
        v, d = list(v), self.d
        for i in range(len(v) - 1, d - 1, -1):
            c = v[i]
            if c:
                for j in range(d + 1):
                    v[i - d + j] -= c * self.f[j]
        return (v + [0] * d)[:d]

    def mul(self, a, b):
        w = [0] * (2 * self.d)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        w[i + j] += x * y
        return self.reduce(w)

    def sigma(self, a, v):
        w = [0] * self.N
        for i, x in enumerate(v):
            if x:
                w[(a * i) % self.N] += x
        return self.reduce(w)


def _mat_inv(M):
    n = len(M)
    A = [[Fraction(x) for x in r] + [Fraction(int(i == j)) for j in range(n)] for i, r in enumerate(M)]
    for c in range(n):
        piv = next(i for i in range(c, n) if A[i][c] != 0)
        A[c], A[piv] = A[piv], A[c]
        pv = A[c][c]
        A[c] = [x / pv for x in A[c]]
        for i in range(n):
            if i != c and A[i][c] != 0:
                f = A[i][c]
                A[i] = [x - f * y for x, y in zip(A[i], A[c])]
    return [r[n:] for r in A]


def exponentes(n, k, mu):
    """eigenvalues of g_mu on C^n as powers of zeta_N, N = n(n+k): n l_i - L mod N."""
    q = n + k
    l = ells(n, mu)
    L = sum(l)
    return [(n * x - L) % (n * q) for x in l], n * q


def orden_columna(n, k, mu):
    """[O:A], [A:f], [O:f] and the Gorenstein test for the column mu of SU(n)_k, any height.
    A = Z[e_1..e_{n-1}] of the eigenvalues; O = Z[zeta_N]^H, the H-fixed sublattice
    (H = the a in (Z/N)^x permuting the eigenvalue exponents); f = {x in O : xO in A}."""
    X, N = exponentes(n, k, mu)
    if N > ORDEN_MAX:
        raise ValueError("N = n(n+k) = %d above ORDEN_MAX = %d" % (N, ORDEN_MAX))
    C = _Cyc(N)
    dz = C.d
    ms = sorted(X)
    H = [a for a in range(2, N) if gcd(a, N) == 1 and sorted(a * x % N for x in X) == ms]
    gens = []
    for j in range(1, n):
        v = [0] * N
        for S in combinations(X, j):
            v[sum(S) % N] += 1
        gens.append(C.reduce(v))
    uno = C.reduce([1])
    base = [C.reduce([0] * i + [1]) for i in range(dz)]
    if H:
        filas = []
        for i in range(dz):
            blk = []
            for a in H:
                s = C.sigma(a, base[i])
                blk += [s[t] - base[i][t] for t in range(dz)]
            filas.append(blk + base[i])
        ncp = len(H) * dz
        _, ker = echelon(filas, ncp)
        ker = [r[ncp:] for r in ker]
    else:
        ker = base
    W, _ = echelon(ker, dz)
    d = len(W)
    piv = [next(t for t, y in enumerate(r) if y) for r in W]

    def co(x):
        c = []
        for i, pc in enumerate(piv):
            v = x[pc] - sum(c[j] * W[j][pc] for j in range(i))
            if v % W[i][pc]:
                raise AssertionError("element outside O")
            c.append(v // W[i][pc])
        if [sum(c[i] * W[i][t] for i in range(d)) for t in range(dz)] != list(x):
            raise AssertionError("element outside O")
        return c

    def full(c):
        return [sum(c[i] * W[i][t] for i in range(d)) for t in range(dz)]

    P, _ = echelon([co(x) for x in [uno] + gens], d)
    while True:
        el = [full(c) for c in P]
        P2, _ = echelon([co(x) for x in el + [C.mul(a, g) for a in el for g in gens]], d)
        if P2 == P:
            break
        P = P2
    if len(P) != d:
        raise AssertionError("A does not have full rank")
    OA = _det_tri(P)
    Pinv = _mat_inv(P)
    Wf = [full([int(i == j) for j in range(d)]) for i in range(d)]
    cols = []
    for i in range(d):
        Mi = [co(C.mul(Wf[j], Wf[i])) for j in range(d)]
        Qi = [[sum(Mi[j][l] * Pinv[l][m] for l in range(d)) for m in range(d)] for j in range(d)]
        cols += [[Qi[j][m] for j in range(d)] for m in range(d)]
    D = 1
    for c in cols:
        for x in c:
            D = D * x.denominator // gcd(D, x.denominator)
    Lh, _ = echelon([[D * int(i == j) for j in range(d)] for i in range(d)]
                    + [[int(D * x) for x in c] for c in cols], d)
    Of = Fraction(D ** d, _det_tri(Lh))
    if Of.denominator != 1 or int(Of) % OA:
        raise AssertionError("conductor index inconsistent")
    Of = int(Of)
    return dict(N=N, exponentes=X, H=len(H) + 1, grado=d, OA=OA, Af=Of // OA, Of=Of,
                gorenstein=(Of // OA == OA))


# --------------------------------------------------------------------------- counts

def centrados(p, n):
    """one representative (sorted tuple) of every F_p^x-orbit of centred n-subsets of F_p."""
    vistos, out = set(), []
    for T in combinations(range(p), n):
        if sum(T) % p:
            continue
        clave = min(tuple(sorted(a * t % p for t in T)) for a in range(1, p))
        if clave not in vistos:
            vistos.add(clave)
            out.append(clave)
    return out


def _Z(p, e, d):
    """number of d-subsets of the subgroup of order e of F_p^x with sum 0."""
    g = next(x for x in range(2, p) if all(pow(x, (p - 1) // r, p) != 1
                                           for r in range(2, p) if (p - 1) % r == 0 and es_primo(r)))
    G = [pow(g, (p - 1) // e * i, p) for i in range(e)]
    return sum(1 for U in combinations(G, d) if sum(U) % p == 0)


def maximales(p, n):
    """N_0(p, n) = n sum_{h | p-1, h > 1, n mod h in {0,1}} [C(e, n//h) - Z_{p,e}(n//h)]."""
    tot = 0
    for h in range(2, p):
        if (p - 1) % h == 0 and n % h in (0, 1):
            e, d = (p - 1) // h, n // h
            tot += comb(e, d) - _Z(p, e, d)
    return n * tot


def maximales_enumeradas(p, n):
    """the same count, by enumerating centred spectra (each stands for n columns)."""
    c = 0
    for T in combinations(range(p), n):
        if sum(T) % p == 0 and not semigrupo(s_exacto(T, p))["huecos"]:
            c += n
    return c


# --------------------------------------------------------------------------- one column

def columna(n, k, mu):
    s = espectro(n, k, mu)
    p, T = s["p"], s["T"]
    H = estabilizador(T, p)
    h, e = len(H), (p - 1) // len(H)
    G = semigrupo(gamma_T(T, p))
    S = semigrupo(s_exacto(T, p))
    d = S["genero"]
    return dict(s, h=h, e=e, momentos=[momento(T, r, p) for r in range(1, min(n, p - 1) + 1)],
                Gamma=G, S=S, delta=d, indice=p ** (phi(s["m"]) * d),
                grado=phi(s["m"]) * e, gorenstein=S["simetrico"])


def _texto_columna(n, k, mu):
    c = columna(n, k, mu)
    S = c["S"]
    out = ["SU(%d)_%d, mu = %s, height p = %d" % (n, k, tuple(mu), c["p"]),
           "   spectrum T = %s, stabiliser order h = %d, e = %d" % (c["T"], c["h"], c["e"]),
           "   central scalar of order m = %d, charge %d, conformal weight %s mod 1"
           % (c["m"], c["carga"], c["peso"]),
           "   moments M_1..M_%d = %s" % (len(c["momentos"]), c["momentos"]),
           "   S_T = <%s>, gaps %s, conductor %d, %s" % (",".join(map(str, S["minimales"])), S["huecos"],
                                                       S["conductor"], "symmetric" if S["simetrico"]
                                                       else "NOT symmetric"),
           "   Gamma_T = S_T: %s" % (c["Gamma"]["huecos"] == S["huecos"]),
           "   [O_mu : A_mu] = p^(phi(m) delta) = %d^%d; field degree %d; %s"
           % (c["p"], phi(c["m"]) * c["delta"], c["grado"], "Gorenstein" if c["gorenstein"]
              else "not Gorenstein")]
    return "\n".join(out)


# --------------------------------------------------------------------------- self-test

def _linea(ok, texto):
    print("   %-78s %s" % (texto, "ok" if ok else "*** FAILED ***"))
    return 0 if ok else 1


def _declina(f, *a):
    try:
        f(*a)
    except ValueError:
        return True
    return False


def autotest():
    f = 0
    print("the first column that is not Gorenstein: SU(5)_12, mu = (0,0,2,1)")
    c = columna(5, 12, (0, 0, 2, 1))
    f += _linea(c["T"] == [1, 2, 3, 13, 15] and c["momentos"] == [0, 0, 15, 13, 2] and c["h"] == 1,
                "T = %s, M_1..M_5 = %s, h = %d" % (c["T"], c["momentos"], c["h"]))
    f += _linea(c["S"]["minimales"] == [3, 4, 5] and c["S"]["huecos"] == [1, 2] and not c["gorenstein"],
                "S_T = <3,4,5>, gaps {1,2}, not symmetric")
    f += _linea(c["m"] == 1 and c["indice"] == 17 ** 2, "m = 1, [O:A] = 17^2 by the semigroup")
    r = orden_columna(5, 12, (0, 0, 2, 1))
    f += _linea((r["OA"], r["Af"], r["gorenstein"]) == (289, 17, False),
                "by integer lattices: [O:A] = %s, [A:f] = %s, not Gorenstein"
                % (factor_str(r["OA"]), factor_str(r["Af"])))
    r0 = orden_columna(5, 12, (0, 0, 0, 0))
    f += _linea((r0["OA"], r0["Af"]) == (1, 1), "control mu = 0: [O:A] = [A:f] = 1")
    print("small n: every semigroup is N_0, <2,3> or <3,4>")
    ok = all(tuple(semigrupo(gamma_T(T, p))["huecos"]) in ((), (1,), (1, 2, 5))
             for p in (7, 11, 13, 17, 19) for n in (3, 4) if n <= p - 2 for T in centrados(p, n))
    f += _linea(ok, "n = 3, 4 and p <= 19: only N_0, <2,3>, <3,4>")
    first = None
    for n in (5, 6):
        for p in (7, 11, 13, 17):
            if n <= p - 2 and first is None:
                for T in centrados(p, n):
                    if not semigrupo(s_exacto(list(T), p))["simetrico"]:
                        first = (n, p)
                        break
    f += _linea(first == (5, 17), "first non-symmetric S_T, by n and then p: n = 5, p = 17")
    print("the index is the number of gaps: delta by lattices = g(S_T) = g(Gamma_T)")
    tot = mal = 0
    for p in (7, 11, 13):
        for n in range(3, min(6, p - 2) + 1):
            for T in centrados(p, n):
                tot += 1
                d = delta_red(T, p)
                if not (d == semigrupo(s_exacto(T, p))["genero"] == semigrupo(gamma_T(T, p))["genero"]):
                    mal += 1
    f += _linea(mal == 0, "%d orbits, 3 <= n <= 6, p <= 13: %d disagreements" % (tot, mal))
    print("the vacuum column is maximal")
    ok = all(columna(n, p - n, (0,) * (n - 1))["delta"] == 0
             for p in (5, 7, 11, 13, 17, 19, 23) for n in range(2, p - 1))
    f += _linea(ok, "mu = 0: delta = 0 for every SU(n)_{p-n}, p <= 23")
    f += _linea(orden_columna(3, 8, (0, 0))["OA"] == 1, "mu = 0 of SU(3)_8 by lattices: [O:A] = 1")
    print("the conformal weight sees M_2")
    ok = all(momento(espectro(4, 7, mu)["T"], 2, 11) == espectro(4, 7, mu)["Q"] * pow(4, -1, 11) % 11
             for mu in pesos(4, 7))
    f += _linea(ok, "M_2(T_mu) = |mu+rho|^2 mod p on all %d columns of SU(4)_7" % len(pesos(4, 7)))
    a, b = columna(6, 11, (0, 0, 0, 0, 1)), columna(6, 11, (0, 2, 0, 0, 5))
    f += _linea(a["peso"] == b["peso"] == Fraction(35, 204) and a["carga"] == b["carga"] == 5
                and a["h"] == b["h"] == 1 and a["grado"] == b["grado"] == 32,
                "SU(6)_11 (0,0,0,0,1), (0,2,0,0,5): weight 35/204, charge 5, h = 1, degree 32")
    f += _linea(a["S"]["minimales"] == [2, 3] and b["S"]["minimales"] == [2, 5]
                and (a["indice"], b["indice"]) == (17 ** 2, 17 ** 4),
                "... and semigroups <2,3>, <2,5>, indices 17^2, 17^4")
    ra, rb = orden_columna(6, 11, (0, 0, 0, 0, 1)), orden_columna(6, 11, (0, 2, 0, 0, 5))
    f += _linea((ra["OA"], rb["OA"]) == (17 ** 2, 17 ** 4), "the two indices again, by integer lattices")
    c = columna(5, 14, (5, 0, 4, 2))
    f += _linea(c["momentos"][1:3] == [1, 0] and c["S"]["minimales"] == [2, 5] and c["indice"] == 19 ** 2,
                "SU(5)_14 (5,0,4,2): M_2 = 1, M_3 = 0, S_T = <2,5>, index 19^2")
    predice_uno = (c["h"] == 1 and c["momentos"][1] != 0)     # the decoy predicts delta = 1
    f += _linea(predice_uno and c["delta"] == 2, "decoy 'delta = 1 <=> h = 1 and M_2 != 0' fails there")
    print("level-rank")
    ok = True
    for n, k in ((3, 4), (3, 8), (5, 6)):
        p = n + k
        A = sorted(tuple(semigrupo(s_exacto(columna(n, k, mu)["T"], p))["huecos"]) for mu in pesos(n, k))
        B = sorted(tuple(semigrupo(s_exacto(columna(k, n, mu)["T"], p))["huecos"]) for mu in pesos(k, n))
        ok &= all(A.count(x) * len(B) == B.count(x) * len(A) for x in set(A) | set(B))
    f += _linea(ok, "SU(n)_k and SU(k)_n: same proportions of semigroups (3,4), (3,8), (5,6)")
    T = [1, 2, 3, 13, 15]
    Tp = sorted((-x) % 17 for x in range(17) if x not in T)
    f += _linea(semigrupo(s_exacto(Tp, 17))["huecos"] == [1, 2] and delta_red(Tp, 17) == 2,
                "T' = -(F_17 minus T) of T = {1,2,3,13,15}: same semigroup, delta = 2")
    print("the maximal columns")
    for p, n, v in ((17, 5, 140), (17, 8, 560), (19, 9, 1233)):
        N0 = maximales(p, n)
        f += _linea(N0 == v == maximales_enumeradas(p, n), "N_0(%d, %d) = %d, formula = enumeration" % (p, n, N0))
    print("the largest defect")
    T = [9, 27, 50, 52, 63]
    pol = [1]
    for t in T:
        pol = [(b - t * a) % 67 for a, b in zip(pol + [0], [0] + pol)]   # times (X - t), low to high
    f += _linea(pol[::-1] == [1, 0, 0, 0, 2, 27], "p = 67, T = %s: polynomial X^5 + 2X + 27" % T)
    S = semigrupo(gamma_T(T, 67))
    f += _linea(S["minimales"] == [4, 5] and S["genero"] == 6 == delta_red(T, 67),
                "Gamma_T = <4,5>, delta = 6 = (n-1)(n-2)/2, by the semigroup and by lattices")
    print("composite height")
    r = orden_columna(3, 11, (0, 1))
    f += _linea((r["OA"], r["Af"], r["gorenstein"]) == (2 ** 8, 2 ** 4, False),
                "SU(3)_11 (q = 14), mu = (0,1): [O:A] = 2^8, [A:f] = 2^4, not Gorenstein")
    print("guards")
    f += _linea(_declina(espectro, 3, 11, (0, 1)), "espectro declines at composite height 14")
    f += _linea(_declina(semigrupo, [2, 4]), "semigrupo declines generators with a common factor")
    f += _linea(_declina(orden_columna, 9, 10, (0,) * 8), "orden_columna declines N above ORDEN_MAX")
    print()
    print("SELF-TEST: all correct" if f == 0 else "SELF-TEST: %d FAILED" % f)
    return f


# --------------------------------------------------------------------------- command line

def main(argv):
    if len(argv) < 2 or argv[1] in ("-h", "--help"):
        print(__doc__)
        return 0
    cmd, a = argv[1], argv[2:]
    try:
        if cmd == "autotest":
            try:
                return 1 if autotest() else 0
            except Exception as ex:
                print("   *** the self-test crashed: %s: %s ***" % (type(ex).__name__, ex))
                print()
                print("SELF-TEST: FAILED (crash)")
                return 1
        if cmd == "columna":
            n, k = int(a[0]), int(a[1])
            mu = tuple(int(x) for x in a[2:])
            if es_primo(n + k) and n + k > 2:
                print(_texto_columna(n, k, mu))
            if n * (n + k) <= ORDEN_MAX:
                r = orden_columna(n, k, mu)
                print("   by integer lattices: [O:A] = %s, [A:f] = %s, degree %d, %s"
                      % (factor_str(r["OA"]), factor_str(r["Af"]), r["grado"],
                         "Gorenstein" if r["gorenstein"] else "NOT Gorenstein"))
            return 0
        if cmd == "espectro":
            p = int(a[0])
            T = sorted(int(x) % p for x in a[1:])
            if sum(T) % p:
                raise ValueError("the spectrum is not centred")
            S = semigrupo(s_exacto(T, p))
            G = semigrupo(gamma_T(T, p))
            print("p = %d, T = %s, h = %d" % (p, T, len(estabilizador(T, p))))
            print("   S_T = <%s>, gaps %s; Gamma_T gaps %s; delta by lattices = %d"
                  % (",".join(map(str, S["minimales"])), S["huecos"], G["huecos"], delta_red(T, p)))
            return 0
        if cmd == "maximales":
            p, n = int(a[0]), int(a[1])
            print("N_0(%d, %d): formula %d, enumeration %d" % (p, n, maximales(p, n), maximales_enumeradas(p, n)))
            return 0
    except ValueError as ex:
        print("declined: %s" % ex)
        return 2
    except IndexError:
        print("missing argument; see  python P3a.py --help")
        return 2
    print("unknown command: %s" % cmd)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
